
server:
  port: 8768
service-url:
  service-hi: http://localhost:8767
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: time_route
          uri: ${service-url.service-hi}/hi
          predicates:
            - Path=/hi
#            - After=2019-11-03T10:20:06+08:00[Asia/Shanghai]
#          - Before=2019-11-03T10:55:06+08:00[Asia/Shanghai]
#          - Between=2019-11-03T11:01:06+08:00[Asia/Shanghai], 2019-11-03T11:05:06+08:00[Asia/Shanghai]
